title: The Github Pages Course
author: Landon Conover
email: landon.conover@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description. Basically I am learning how Github Pages work.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
